### PR TITLE
system: add support for gestures on OnePlus devices

### PR DESCRIPTION
**Pull request by Bettehem**
Tested on OnePlus 3/3T and OnePlus 5

### CODE REVIEW

**Comment by bellegarde-c** [comment]
I guess it's time to remove the *-available keys in gsettings.

We have *-supported properties, gnome-control-center should be able to query those properties via DBus.

Do you want to work on this?

**Comment by Bettehem** [comment]
Yeah sure, but I think its probably better to do in a separate PR as it isn't really oneplus or swipe to wake related. What do you think?

**Comment by bellegarde-c** [comment]
I guess we can merge this one and enhance the code later in another PR, @g7 ?

**Review by g7 — APPROVED** [review]
Thanks, great work! Yes, agreed follow-up can be in another PR :+1:

**Pull request merged**
